baseurl = "https://who-knows.club"
languageCode = "en-us"
title = "Who Knows. A Club"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "who-knows-club"
# Enable google analytics by entering your tracking code
googleAnalytics = "UA-92966370-1"
theme = "hugo-minimalist-theme"

# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
#themesDir = "../.."

[params]
    site_author = "Igor Sokolov"
    site_description = "The personal blog of Igor Sokolov."
    location = "Conshohocken PA, USA"
    # Link custom assets relative to /static
    avatar = "img/myface.jpeg"
    header_background = "img/desk.jpg"
    header_title = "Who knows. A club"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = "UA-92966370-1"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "igor-sokolov"
    gplus     = ""
